application: tekuto-net
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /
  static_files: static/index.html
  upload: static/index.html

- url: /(.*\.(html|js|css|png))
  static_files: static/\1
  upload: static/(.*\.(html|js|css|png))
